#! /bin/bash
if  [ ! -n "$1" ] ;then
	echo "this command is to make the file had been cmade,you should input a parameter,for example,  again test.C"
	exit 1
fi
cd $(pwd)/build_tmp
make -j4
cp $1_exe ..
cd ..
./$1_exe
#rm $1_exe
