#!/bin/bash
if  [ ! -n "$1" ] ;then
	echo "You should input a parameter,for example,  config_root_tool_G4 test.cc"
	echo "OR"
	echo "	input two parameters: config_root_tool_G4 test.cc B1 (the second parameter is the name of the project."
	exit 1
fi

file_name=$1

if [ -L root_tool ]; then
	echo "Removed symbolic link 'root_tool'"
	/bin/rm root_tool
fi
	ln -s /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool .
cp /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/CMakeLists_G4_here_run.txt /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/CMakeLists.txt
cp /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/CMakeLists_G4_ProjectPath_run.txt $(pwd)/CMakeLists.txt

sed -i "s#C_File_target#${file_name%.*}#g" $(pwd)/CMakeLists.txt

if  [ -n "$2" ] ;then
	sed -i "s#ProjectName_target#$2#g" $(pwd)/CMakeLists.txt
else
	echo "You can also add a second parameter to change the Project's name"
fi

if [ ! -d "build" ];then
	mkdir build
else
	/bin/rm -rf build
	mkdir build
fi
cd build
cmake ..
make -j4

cp /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/command/job_G4.sh .
sed -i "s#C_File_target#${file_name%.*}#g" ./job_G4.sh

echo "Configure done! You are able to use"
echo "./job.sh OR ./job.sh MyRun.mac "
echo "To make and run the project!"
#cp $1_exe ..
#cd ..
#./$1_exe
##rm $1_exe
#rm -r build_tmp
#sed -i "s#$1#cmake_target#g" /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/CMakeLists.txt
#sed -i "s#$(pwd)#pwd_target#g" /afs/ihep.ac.cn/users/l/luoxj/workfs_5G/root_tool/CMakeLists.txt

